# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [86]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [87]:
print(np.__version__)

np.show_config()

1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

#### 3. Create a null vector of size 10 (★☆☆)

In [88]:
myarray = np.zeros(10)
myarray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [89]:
myarray.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [90]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [91]:
myarray = np.zeros(10)
myarray[4] = 1
myarray

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [92]:
myarray1 = np.arange(10,50)
myarray1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [93]:
myarray2 = myarray1[::-1]
myarray2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [94]:
myarray = np.arange(0,9).reshape(3,3)
myarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [95]:
myarray = np.array([1,2,0,0,4,0])
np.nonzero(myarray)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [96]:
myarray = np.eye(3)
myarray

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [97]:
myarray = np.random.random((3,3,3))
myarray

array([[[7.03623999e-01, 5.70249298e-01, 3.53529849e-01],
        [6.16349777e-01, 5.88660188e-01, 5.76579759e-01],
        [7.10134170e-01, 5.90044579e-01, 4.29418902e-01]],

       [[8.85304244e-01, 8.07029530e-04, 6.85952556e-01],
        [7.42111620e-01, 4.79331578e-02, 1.22509854e-01],
        [9.25346154e-01, 3.97850576e-01, 1.16455893e-01]],

       [[3.10854537e-01, 1.01767414e-01, 3.01397185e-01],
        [2.76779567e-01, 3.58032986e-01, 6.08462058e-02],
        [8.17552985e-01, 7.73371247e-01, 1.07386519e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [98]:
myarray = np.random.random((10,10))
print(myarray)
print(myarray.max())
print(myarray.min())

[[3.74487307e-01 6.22711081e-01 1.06649798e-01 1.72550916e-01
  2.73865565e-01 8.23798241e-01 4.14853688e-01 1.60051784e-01
  2.18315839e-01 3.25382094e-01]
 [7.59211835e-01 5.21141217e-01 7.86105699e-01 3.96657611e-01
  4.84702758e-01 2.28637026e-01 9.94231106e-01 6.88224171e-01
  8.03362078e-02 3.64750963e-01]
 [7.88517560e-01 1.97526229e-01 5.14311592e-01 4.57273048e-01
  7.95643341e-01 7.19767949e-01 4.95490618e-01 3.06399093e-02
  4.80416179e-01 3.76517084e-01]
 [3.15804344e-01 4.94491774e-01 7.47551805e-01 6.91728963e-01
  2.00248732e-01 7.84726006e-02 1.49515485e-01 6.81448817e-01
  7.66793443e-01 1.66067772e-01]
 [2.73059407e-01 2.48499603e-01 9.42988329e-01 7.17499224e-01
  4.85782220e-04 3.12628601e-01 4.61636500e-01 3.90706445e-01
  4.76839794e-01 2.74077499e-01]
 [8.26173543e-01 3.35186826e-01 4.22611731e-01 2.20106956e-01
  1.33843252e-01 7.35679762e-01 3.93448336e-01 3.62097682e-01
  7.53561049e-01 4.74878600e-02]
 [1.90393891e-01 6.59172543e-02 4.39088858e-01 5.78212905e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [99]:
myarray = np.random.random((30))
print(myarray)
print(myarray.mean())

[0.87482659 0.14460054 0.4168333  0.96916721 0.34669477 0.72988706
 0.70081278 0.51469645 0.24198637 0.06207992 0.09616738 0.68620898
 0.07040692 0.95457339 0.47345677 0.94954733 0.5564258  0.47782558
 0.62596809 0.21660167 0.35231179 0.49604856 0.45494249 0.41376932
 0.87100021 0.73272198 0.31695985 0.09749836 0.13091787 0.20865021]
0.4727862506364044


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [100]:
myarray = np.ones((5,5)) 
myarray[1:-1,1:-1] = 0
myarray

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [101]:
myarray = np.pad(myarray, pad_width=1, mode='constant', constant_values=0)
myarray

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [102]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [103]:
myarray = np.zeros((5,5))
myarray = np.diag(1+np.arange(4), k = -1)
myarray

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [104]:
myarray = np.zeros((8,8))
myarray[1::2, ::2]= 1
myarray[::2, 1::2] = 1
myarray

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [105]:
myarray = np.unravel_index(100, (6,7,8))
myarray

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [106]:
myarray= np.array([[0,1], [1,0]])
myarray = np.tile(myarray,(4,4))
print (myarray)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [107]:
myarray = np.random.random((5,5))
max = myarray.max()
min = myarray.min()
myarray = (myarray - min)/(max - min)
myarray

array([[0.16587868, 0.23393624, 0.2988002 , 0.91715018, 0.52021839],
       [0.4989768 , 0.85524994, 0.15179412, 1.        , 0.86322419],
       [0.74013037, 0.32584221, 0.12432155, 0.61758093, 0.68991657],
       [0.6278244 , 0.22726509, 0.88653171, 0.74012109, 0.        ],
       [0.17394313, 0.06548106, 0.68214247, 0.39942058, 0.68144359]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [108]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
color


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [109]:
myarray = np.dot(np.ones((5,3)), np.ones((3,2)))
myarray

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [110]:
myarray = np.random.randint(0,10,10)
print(myarray)
myarray[(3 < myarray) & (myarray < 8)] = -myarray[(3 < myarray) & (myarray < 8)]
print(myarray)

[4 4 0 2 6 4 4 7 8 1]
[-4 -4  0  2 -6 -4 -4 -7  8  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [111]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [112]:
myarray = np.arange(3)
print(myarray**myarray)
print(2 << myarray >> 2)
print(myarray <- myarray)
print(1j*myarray)
print(myarray/1/1)
print('myarray<myarray>myarray')

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]
myarray<myarray>myarray


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [113]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [114]:
def roundAwayFromZero(array):
    a = np.abs(array)
    b = np.floor(a) + np.floor(2*(a%1))
    return np.copysign(b, array)

x = np.linspace(-5, 5, 20)
roundAwayFromZero(x)

array([-5., -4., -4., -3., -3., -2., -2., -1., -1., -0.,  0.,  1.,  1.,
        2.,  2.,  3.,  3.,  4.,  4.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [115]:
myarray1 = np.random.randint(0,10,10)
myarray2 = np.random.randint(0,10,10)
myarray = np.intersect1d(myarray1,myarray2)
print(myarray1)
print(myarray2)
print(myarray)

[5 6 2 9 5 7 4 2 3 6]
[4 7 2 7 7 5 4 3 4 9]
[2 3 4 5 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [116]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [117]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [118]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-11-26
2022-11-27
2022-11-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [119]:
days = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
days

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [120]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)
A

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [121]:
myarray = np.random.uniform(0,10,10)

print(myarray - myarray%1)
print(myarray // 1)
print(np.floor(myarray))
print(myarray.astype(int))
print(np.trunc(myarray))

[4. 2. 1. 1. 2. 4. 5. 3. 3. 4.]
[4. 2. 1. 1. 2. 4. 5. 3. 3. 4.]
[4. 2. 1. 1. 2. 4. 5. 3. 3. 4.]
[4 2 1 1 2 4 5 3 3 4]
[4. 2. 1. 1. 2. 4. 5. 3. 3. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [122]:
myarray = np.zeros((5,5))
myarray += np.arange(5)
myarray

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [123]:
def generate():
    for x in range(10):
        yield x
myarray = np.fromiter(generate(),dtype=float,count=-1)
myarray

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [124]:
myarray = np.linspace(0,1,11,endpoint=False)[1:]
myarray

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [125]:
myarray = np.random.randint(0,10,10)
myarray.sort()
myarray

array([0, 1, 3, 3, 3, 4, 4, 5, 6, 6])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [126]:
myarray = np.random.randint(0,10,10)
print(myarray)
print(np.add.reduce(myarray))

[4 1 3 2 8 6 3 5 1 8]
41


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [127]:
myarrayA = np.random.randint(0,10,10)
myarrayB = np.random.randint(0,10,10)
result = np.allclose(myarrayA, myarrayB)
print(myarrayA)
print(myarrayB)
print(result)

[0 2 2 9 2 6 1 3 0 0]
[2 0 4 4 3 3 9 4 3 0]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [128]:
myarray = np.zeros(10)
myarray.flags.writeable = False
'myarray[1] = 100'
print(myarray.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False



#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [129]:
myarray = np.random.random((10,2))
x = myarray[:,0]
y = myarray[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(myarray)
print(r)
print(t)

[[0.69848855 0.16352381]
 [0.59411219 0.49155071]
 [0.07165646 0.47983773]
 [0.23958641 0.18734252]
 [0.50414159 0.63795937]
 [0.43678269 0.54234891]
 [0.89614293 0.60612867]
 [0.88964901 0.66522868]
 [0.59815252 0.30957847]
 [0.98978259 0.89994751]]
[0.71737458 0.77109752 0.48515862 0.30413626 0.81311186 0.69636302
 1.0818799  1.11085758 0.67351708 1.33775001]
[0.22996926 0.6912087  1.42255702 0.66363216 0.90203444 0.89279945
 0.59469367 0.64205496 0.47759495 0.73789535]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [130]:
myarray = np.random.random((10))
print(myarray)
max = myarray.argmax()
myarray[max] = 0
print(max)
print(myarray)

[0.05330473 0.05077788 0.2520305  0.29080201 0.35906134 0.08312605
 0.13118733 0.51373585 0.42843051 0.4398534 ]
7
[0.05330473 0.05077788 0.2520305  0.29080201 0.35906134 0.08312605
 0.13118733 0.         0.42843051 0.4398534 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [131]:
myarray = np.zeros((5,5), [('x',float),('y',float)])
myarray['x'], myarray['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(myarray)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [132]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(c)
c = np.linalg.det(c)
print(c)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [133]:
print(np.iinfo(np.int8).min)
print(np.iinfo(np.int8).max)
print(np.iinfo(np.int16).min)
print(np.iinfo(np.int16).max)
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)
print(np.finfo(np.float32).min)
print(np.finfo(np.float32).max)
print(np.finfo(np.float32).eps)
print(np.finfo(np.float64).min)
print(np.finfo(np.float64).max)
print(np.finfo(np.float64).eps)

-128
127
-32768
32767
-2147483648
2147483647
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [134]:
np.set_printoptions(threshold=float("inf"))
myarray = np.random.random((50,50))
print(myarray)

[[3.47534320e-01 8.25755014e-01 3.24646757e-01 7.20497513e-01
  4.23310154e-01 6.78450697e-01 5.53850512e-01 3.19003782e-01
  6.46786377e-01 7.78761203e-01 5.03513643e-01 2.06449365e-01
  4.05618117e-01 2.31443635e-01 1.79795381e-01 3.49989813e-01
  6.74146915e-01 1.00263291e-02 8.51327268e-01 8.02244728e-01
  9.54587396e-01 1.59963949e-01 6.25037466e-01 1.15807597e-01
  1.27232900e-01 5.04322425e-01 3.23614775e-01 7.80644400e-01
  3.88096872e-01 9.95790476e-01 8.28990024e-01 8.80139817e-03
  1.32046929e-01 6.10761675e-01 2.82145507e-01 7.35252433e-01
  9.41159010e-01 2.60638217e-01 6.68040707e-01 5.51821996e-01
  1.39317386e-01 7.42952452e-01 4.49382531e-01 4.25114050e-01
  3.26087726e-01 8.57006527e-01 8.61672525e-01 8.94482239e-01
  1.49367701e-01 3.53153338e-01]
 [1.44895388e-01 4.08437764e-01 4.66400827e-01 3.93337389e-01
  6.59904388e-01 9.25108124e-01 9.69806063e-01 8.55836470e-02
  2.56180347e-01 7.01056452e-01 8.44984799e-01 4.92403496e-01
  2.43454984e-01 3.63831652e-01 8.397

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [135]:
myarray = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(myarray-v)).argmin()
print(myarray)
print(v)
print(myarray[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
91.18832738482276
91


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [136]:
array = np.zeros(10, [('position', [('x', float),('y', float)]),
                     ('color', [('r', float),('g', float),('b', float)])])
array

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [137]:
myarray = np.random.random((100,2))
x,y = np.atleast_2d(myarray[:,0], myarray[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.59445563 0.37475622 0.91263388 0.94462915 0.23026172
  0.8681925  0.30546889 0.54427903 0.47067116 0.56553875 0.78679203
  0.7218648  0.94607474 0.35324917 0.89206125 0.10428217 0.36779588
  0.49961546 0.84079202 0.27077282 0.85728288 0.83076532 0.53747113
  0.41147263 0.39844082 0.03719066 0.27397193 0.2442015  0.48980972
  0.48115021 0.34325281 0.53987616 0.50412165 0.72153247 0.8089082
  0.82509163 0.51506649 0.70290598 0.45867249 0.16389884 0.80460098
  0.185563   0.29552376 0.42550526 0.47469159 0.43855118 0.23142455
  0.46921918 0.25399881 0.55303106 0.71580512 0.3312901  0.4016414
  0.28235716 0.12624247 0.13481736 0.23806371 0.96595086 0.10941695
  0.8032965  0.31375457 0.42664801 0.21832224 0.45057135 0.56559992
  0.64480378 0.26431117 0.77725743 0.39845263 0.3740732  0.28181178
  0.85140365 0.37331558 0.76456896 0.76224182 0.54908211 0.70296726
  0.37342912 0.43692689 0.42941823 0.3018336  0.16243707 0.55301924
  0.25314024 0.63960396 0.43441322 0.78135047 0.89

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [138]:
myarray = (np.random.rand(10)*100).astype(np.float32)
myarray1 = myarray.view(np.int32)
myarray1[:] = myarray
print(myarray)
print(myarray1)

[1.35e-43 2.80e-44 1.26e-43 9.81e-45 2.52e-44 7.57e-44 8.41e-44 1.30e-43
 1.68e-44 1.18e-43]
[96 20 90  7 18 54 60 93 12 84]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [139]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')
myarray = np.genfromtxt(s, delimiter=",", dtype=np.int, filling_values=0)
myarray

C:\Users\admin\AppData\Local\Temp\ipykernel_22408\445262623.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  myarray = np.genfromtxt(s, delimiter=",", dtype=np.int, filling_values=0)


array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  7,  8],
       [ 0,  0,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [140]:
myarray = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(myarray):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [141]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [142]:
n = 5
p = 10
myarray = np.zeros((n,n))
np.put(myarray, np.random.choice(range(n*n), p, replace=False),1)
print(myarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [143]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y

array([[ 0.25526115,  0.53702555,  0.38168031,  0.03098996, -0.03142627,
        -0.40442811,  0.16514272, -0.37186553, -0.35903737, -0.20334241],
       [-0.45205327,  0.07655821,  0.07827856, -0.01747673,  0.31909847,
         0.02200597,  0.22670908, -0.34000469,  0.23492318, -0.14803876],
       [-0.48827187,  0.05105618,  0.2616353 ,  0.30022603,  0.27676642,
        -0.45251366, -0.01430849,  0.33179214, -0.28507523,  0.01869318],
       [-0.10650548,  0.28742552, -0.40641764, -0.26118037, -0.15665871,
        -0.27612519,  0.21897246,  0.41585829,  0.16607962,  0.11855151],
       [-0.10838436,  0.45100095,  0.0053073 , -0.32236496, -0.19119379,
        -0.0707733 ,  0.17275321, -0.01697604,  0.17518941, -0.09455842]])

#### 59. How to sort an array by the nth column? (★★☆)

In [144]:
myarray = np.random.randint(0,10,(3,3))
print(myarray)
myarray = myarray[myarray[:,1].argsort()]
print(myarray)

[[4 6 4]
 [5 2 3]
 [6 9 8]]
[[5 2 3]
 [4 6 4]
 [6 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [145]:
myarray = np.random.randint(0,3,(4,10))
print(myarray)
bool = (~myarray.any(axis=0)).any()
print(bool)

[[2 0 1 2 1 0 0 1 2 2]
 [0 0 2 2 2 2 1 2 1 1]
 [1 1 0 1 1 1 1 0 2 2]
 [0 0 1 0 2 1 1 0 2 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [146]:
myarray = np.random.uniform(1, 12, 5)
v = 4
n = myarray.flat[np.abs(myarray - v).argmin()]
print(myarray)
print(n)

[ 3.43123271  4.24409544  9.35354973 10.21329973  9.00705482]
4.244095437771044


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [147]:
myarrayA = np.arange(3).reshape(3,1)
myarrayB = np.arange(3).reshape(1,3)
it = np.nditer([myarrayA,myarrayB,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [148]:
class ArrayClass(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

myarray = ArrayClass(np.arange(10), "range_10")
print (myarray.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [149]:
myarray = np.ones(10)
i = np.random.randint(0,len(myarray),20)
myarray += np.bincount(i, minlength=len(myarray))
print(myarray)

[3. 3. 5. 3. 2. 5. 2. 4. 2. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [150]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,x)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [151]:
w = 256
h = 256
i = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(i.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [152]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)

[[43 63 41 59]
 [48 63 62 41]
 [42 46 52 53]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [153]:
d = np.random.uniform(0,1,100)
s = np.random.randint(0,10,100)
d_sums = np.bincount(s, weights=d)
d_counts = np.bincount(s)
d_means = d_sums / d_counts
print(d)
print(s)
print(d_means)

[0.98342539 0.42575199 0.78258173 0.96298419 0.75019833 0.94519077
 0.47138601 0.00603359 0.2144755  0.38877591 0.87858877 0.84548317
 0.2064984  0.7778791  0.70954238 0.57493184 0.87473392 0.30623921
 0.38079701 0.73389314 0.58805296 0.3055465  0.46883822 0.47530369
 0.35640934 0.05282761 0.57541796 0.17022656 0.8300005  0.81845325
 0.50576723 0.16179918 0.41010208 0.86667974 0.84884328 0.43896028
 0.99475284 0.19008841 0.58597741 0.32917281 0.60320623 0.97274849
 0.69781989 0.23386879 0.45178222 0.88047383 0.69792607 0.45180124
 0.8269731  0.87608322 0.14290211 0.97908593 0.27388415 0.73657108
 0.99861305 0.40121475 0.38268877 0.64295021 0.02286653 0.43664484
 0.72908636 0.31308719 0.83900387 0.52363406 0.78209129 0.17704034
 0.01521709 0.26814753 0.38653469 0.52406778 0.01768734 0.31880626
 0.45528514 0.65780135 0.5082213  0.83065326 0.79608717 0.04638011
 0.03028259 0.79636625 0.71750104 0.43494575 0.66326178 0.89772674
 0.98769078 0.42203237 0.69912838 0.92909189 0.50513946 0.9222

#### 69. How to get the diagonal of a dot product? (★★★)

In [154]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))
np.diag(np.dot(a, b))

array([1.5803482 , 0.52061224, 0.73058753, 1.82069703, 0.68960589])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [155]:
myarray = np.array([1,2,3,4,5])
zeros = 3
myarray0 = np.zeros(len(myarray) + (len(myarray)-1)*(zeros))
myarray0[::zeros+1] = myarray
print(myarray0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [156]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [157]:
a = np.arange(9).reshape(3,3)
a[[0,1]] = a[[1,0]]
print(a)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [158]:
myarray = np.random.randint(0,100,(10,3))
f = np.roll(myarray.repeat(2,axis=1),-1,axis=1)
f = f.reshape(len(f)*3,2)
f = np.sort(f,axis=1)
g = f.view( dtype=[('p0',f.dtype),('p1',f.dtype)] )
g = np.unique(g)
print(g)

[( 7, 32) ( 7, 39) ( 9, 70) ( 9, 77) ( 9, 84) ( 9, 85) (12, 14) (12, 89)
 (14, 89) (24, 85) (24, 99) (29, 31) (29, 79) (31, 79) (32, 39) (35, 45)
 (35, 58) (45, 57) (45, 58) (45, 69) (50, 93) (52, 64) (52, 65) (57, 69)
 (64, 65) (70, 85) (77, 84) (85, 99) (93, 93)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [159]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [160]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
myarray = np.arange(20)
print(moving_average(myarray, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [161]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
myarray = rolling(np.arange(10), 3)
print(myarray)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [162]:
myarray = np.random.randint(0,2,100)
np.logical_not(myarray, out=myarray)

myarray = np.random.uniform(-1.0,1.0,100)
np.negative(myarray, out=myarray)

array([-0.6566221 ,  0.24742808, -0.08898993,  0.76681917, -0.95180948,
       -0.09156733,  0.52917663, -0.65070779, -0.0923564 , -0.66657917,
        0.61909117,  0.06655474, -0.49133641,  0.57216522, -0.18335547,
       -0.30173301,  0.82674877,  0.05233553, -0.81241456, -0.99945183,
        0.93816622,  0.85470734,  0.2893691 ,  0.87325558, -0.55919483,
        0.73626077, -0.63991628,  0.54290594,  0.97733201, -0.90809421,
       -0.84621166, -0.22846464, -0.6296815 ,  0.6332374 , -0.44718037,
        0.31700545,  0.81352618, -0.31145741, -0.07247246,  0.45794777,
        0.3115938 , -0.70875433,  0.7428381 ,  0.70948317, -0.89664693,
        0.98478389, -0.04507265,  0.65544257, -0.14832301, -0.69096441,
        0.98931039, -0.01419886, -0.15487305, -0.12222975, -0.35782231,
       -0.67798552, -0.96630938,  0.82818714,  0.01189921,  0.28235577,
        0.56628003,  0.35035597,  0.13898277,  0.5070003 ,  0.73798047,
        0.06977633, -0.01373288,  0.30336621,  0.37673187,  0.96

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [163]:
def distance(p0, p1, p):
    t = p1 - p0
    l = (t**2).sum(axis=1)
    u = -((p0[:,0]-p[...,0])*t[:,0] + (p0[:,1]-p[...,1])*t[:,1]) / l
    u = u.reshape(len(u),1)
    d = p0 + u*t - p
    return np.sqrt((d**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.22223967  5.61359058 10.17503469  2.05747328  1.32060926  3.36876506
 10.86167853  4.56610843  1.02444287 13.13597606]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [164]:
p0 = np.random.uniform(-10, 10, (10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(p0,p1,p_i) for p_i in p]))

[[10.28008161 13.89468292 15.41606386  0.11071785  5.03379972  3.41609708
  12.66228844  7.43329118  0.78266701 13.58976033]
 [ 3.21553985  0.57811717  2.91575227  5.24689058  6.20245461  3.84257856
   0.7828198  13.33390973  2.91993196  0.71147569]
 [ 9.79469776 13.11313432 15.80591738  1.67791509  3.49406722  1.39508069
  12.03467732  9.52899674  2.6961518  12.53482326]
 [ 1.71543921  5.7351726   6.67443619  5.27119357  1.0030623   0.50492938
   4.26846055  9.36360414  3.53863079  5.98693348]
 [ 6.64095622  8.7433078  16.37431893  8.68092377  3.85241915  7.61728861
   8.29394882 18.7375338  10.33884149  7.06541317]
 [ 0.45450652  3.29943703  5.48170447  4.17600307  3.91522129  2.37546416
   1.96641259 12.14589437  2.14158928  3.34018482]
 [ 1.7509483   1.72406966  5.10234495  2.73828966  6.10591699  4.79503363
   0.53386302 14.55589203  0.49443837  1.52395901]
 [ 6.27335597  8.59884865 15.4283548   7.11766886  3.33938105  6.54557973
   8.03162113 17.53973109  8.76177068  7.14145261]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [171]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

print(Z)
print(R)

[[1 0 9 2 9 6 7 2 4 0]
 [8 5 3 7 7 1 3 5 2 3]
 [9 5 1 1 6 8 2 5 3 4]
 [2 2 7 3 7 4 2 7 2 6]
 [6 9 3 3 8 4 9 0 0 0]
 [7 1 7 9 2 1 5 0 0 0]
 [4 0 2 7 4 7 8 8 6 8]
 [5 6 0 0 7 7 4 3 7 3]
 [4 8 7 3 9 4 4 6 6 6]
 [7 4 8 6 4 3 9 1 3 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [85]:
myarray = np.arange(1,15,dtype=np.uint32)
myarray = stride_tricks.as_strided(myarray,(11,4),(4,4))
print(myarray)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [35]:
myarray = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(myarray)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [38]:
myarray = np.random.randint(0,10,50)
print(myarray)
print(np.bincount(myarray).argmax())

[1 7 0 2 1 8 6 7 3 0 0 4 8 1 0 4 1 2 2 8 3 1 0 0 2 0 3 4 5 1 7 7 7 8 9 6 8
 3 2 9 8 2 4 5 0 9 8 8 2 8]
8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [42]:
myarray = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (myarray.shape[0]-3)
j = 1 + (myarray.shape[1]-3)
c = stride_tricks.as_strided(myarray, shape=(i, j, n, n), strides=myarray.strides + myarray.strides)
print(myarray)
print(c)

[[4 3 4 3 3 4 2 1 3 1]
 [4 1 4 4 0 1 2 2 0 2]
 [1 1 1 0 4 0 2 4 3 2]
 [4 4 1 1 0 0 2 1 1 1]
 [2 3 0 3 1 0 2 2 2 4]
 [1 3 2 4 4 0 3 2 4 2]
 [3 4 4 4 0 1 0 3 0 0]
 [2 4 3 0 2 4 2 0 2 0]
 [0 3 3 1 2 1 3 3 2 4]
 [1 2 0 2 3 2 3 0 4 2]]
[[[[4 3 4]
   [4 1 4]
   [1 1 1]]

  [[3 4 3]
   [1 4 4]
   [1 1 0]]

  [[4 3 3]
   [4 4 0]
   [1 0 4]]

  [[3 3 4]
   [4 0 1]
   [0 4 0]]

  [[3 4 2]
   [0 1 2]
   [4 0 2]]

  [[4 2 1]
   [1 2 2]
   [0 2 4]]

  [[2 1 3]
   [2 2 0]
   [2 4 3]]

  [[1 3 1]
   [2 0 2]
   [4 3 2]]]


 [[[4 1 4]
   [1 1 1]
   [4 4 1]]

  [[1 4 4]
   [1 1 0]
   [4 1 1]]

  [[4 4 0]
   [1 0 4]
   [1 1 0]]

  [[4 0 1]
   [0 4 0]
   [1 0 0]]

  [[0 1 2]
   [4 0 2]
   [0 0 2]]

  [[1 2 2]
   [0 2 4]
   [0 2 1]]

  [[2 2 0]
   [2 4 3]
   [2 1 1]]

  [[2 0 2]
   [4 3 2]
   [1 1 1]]]


 [[[1 1 1]
   [4 4 1]
   [2 3 0]]

  [[1 1 0]
   [4 1 1]
   [3 0 3]]

  [[1 0 4]
   [1 1 0]
   [0 3 1]]

  [[0 4 0]
   [1 0 0]
   [3 1 0]]

  [[4 0 2]
   [0 0 2]
   [1 0 2]]

  [[0 2 4]
   [0 2 1]
   [0 2 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [43]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(z):
    return np.asarray(z + z.T - np.diag(z.diagonal())).view(Symetric)

s = symetric(np.random.randint(0,10,(5,5)))
s[2,3] = 42
print(s)

[[ 1  6 11  6  3]
 [ 6  2  7  5  5]
 [11  7  7 42 11]
 [ 6  5 42  3 11]
 [ 3  5 11 11  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [45]:
p = 10 
n = 20
m = np.ones((p,n,n))
v = np.ones((p,n,1))
s = np.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [172]:
myarray = np.ones((16,16))
k = 4
s = np.add.reduceat(np.add.reduceat(myarray, np.arange(0, myarray.shape[0], k), axis=0),
                                       np.arange(0, myarray.shape[1], k), axis=1)
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [173]:
def iterate(myarray):
    # Count neighbours
    n = (myarray[0:-2,0:-2] + myarray[0:-2,1:-1] + myarray[0:-2,2:] +
         myarray[1:-1,0:-2]                + myarray[1:-1,2:] +
         myarray[2:  ,0:-2] + myarray[2:  ,1:-1] + myarray[2:  ,2:])

    # Apply rules
    birth = (n==3) & (myarray[1:-1,1:-1]==0)
    survive = ((n==2) | (n==3)) & (myarray[1:-1,1:-1]==1)
    myarray[...] = 0
    myarray[1:-1,1:-1][birth | survive] = 1
    return myarray

myarray = np.random.randint(0,2,(50,50))
for i in range(100): myarray = iterate(myarray)
print(myarray)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [54]:
myarray = np.arange(10)
np.random.shuffle(myarray)
n = 5
print (myarray[np.argsort(myarray)[-n:]])

[5 6 7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [55]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [56]:
myarray = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(myarray.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [174]:
x = np.random.rand(int(100000))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

6.83 ms ± 416 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.41 ms ± 48.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
218 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [11]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[0 1 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [178]:
myarray = np.random.randint(0,5,(10,3))
print(myarray)
e = np.all(myarray[:,1:] == myarray[:,:-1], axis=1)
u = myarray[~e]
print(u)
u = myarray[myarray.max(axis=1) != myarray.min(axis=1),:]
print(u)

[[0 2 0]
 [0 4 4]
 [0 2 0]
 [2 0 2]
 [0 3 2]
 [2 1 1]
 [1 1 0]
 [3 4 3]
 [1 3 0]
 [4 3 3]]
[[0 2 0]
 [0 4 4]
 [0 2 0]
 [2 0 2]
 [0 3 2]
 [2 1 1]
 [1 1 0]
 [3 4 3]
 [1 3 0]
 [4 3 3]]
[[0 2 0]
 [0 4 4]
 [0 2 0]
 [2 0 2]
 [0 3 2]
 [2 1 1]
 [1 1 0]
 [3 4 3]
 [1 3 0]
 [4 3 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [14]:
myarray = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(myarray[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [184]:
myarray = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(myarray).view(np.dtype((np.void, myarray.dtype.itemsize * myarray.shape[1])))
_, idx = np.unique(T, return_index=True)
umyarray = myarray[idx]
print(umyarray)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [22]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.75590243, 0.35294202, 0.52917566, 0.45863999, 0.77103817,
        0.23868678, 0.59389642, 0.02728906, 0.73924307, 0.37015477],
       [0.19959012, 0.09319158, 0.13972469, 0.1211003 , 0.20358659,
        0.06302337, 0.1568137 , 0.00720546, 0.19519134, 0.09773647],
       [0.5962712 , 0.27840784, 0.41742452, 0.36178454, 0.60821058,
        0.18828098, 0.46847757, 0.02152616, 0.58312996, 0.2919856 ],
       [0.63791712, 0.29785294, 0.44657908, 0.38705299, 0.65069039,
        0.20143126, 0.50119788, 0.02302963, 0.62385804, 0.31237902],
       [0.43869758, 0.20483439, 0.30711382, 0.26617754, 0.44748179,
        0.1385249 , 0.34467533, 0.01583755, 0.42902911, 0.21482402],
       [0.58841265, 0.27473857, 0.41192307, 0.35701641, 0.60019467,
        0.18579953, 0.46230327, 0.02124246, 0.5754446 , 0.28813738],
       [0.44670339, 0.20857242, 0.31271835, 0.27103503, 0.45564791,
        0.14105285, 0.35096533, 0.01612657, 0.43685848, 0.21874435],
       [0.89728444, 0.41895537, 0.6281512

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [182]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print(r_int)
print(x_int)
print(y_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [25]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
m = np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
m &= (x.sum(axis=-1) == n)
print(x[m])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [26]:
x = np.random.randn(100) # random 1D array
n = 1000 # number of bootstrap samples
idx = np.random.randint(0, x.size, (n, x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23846818  0.15148558]
